//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NegociosElectronicosII.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NE_AutenticacionConEmail
    {
        public int ID_AutenticacionConEmail { get; set; }
        public string Email { get; set; }
        public System.DateTime FechaDeSolicitud { get; set; }
        public System.DateTime FechaDeVencimiento { get; set; }
        public string CodigoDeVerificacion { get; set; }
        public bool CodigoConfirmado { get; set; }
    }
}
