//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NegociosElectronicosII.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NE_Bitacora
    {
        public int BitacoraId { get; set; }
        public int AccionId { get; set; }
        public string Descripcion { get; set; }
        public System.DateTime FechaDeRegistro { get; set; }
        public int UsuarioId { get; set; }
    
        public virtual NE_Accion NE_Accion { get; set; }
        public virtual NE_Usuario NE_Usuario { get; set; }
    }
}
