//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NegociosElectronicosII.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NE_Carrusel
    {
        public int CarruselId { get; set; }
        public int Posicion { get; set; }
        public string Texto { get; set; }
        public string Descripcion { get; set; }
        public string Ruta { get; set; }
        public string Extension { get; set; }
        public string NombreArchivo { get; set; }
        public bool Activo { get; set; }
    }
}
