//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NegociosElectronicosII.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NE_EmailTemplate
    {
        public int EmailTemplateId { get; set; }
        public string EmailTemplate { get; set; }
        public string Name { get; set; }
        public bool Active { get; set; }
    }
}
