//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NegociosElectronicosII.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NE_Template
    {
        public int TemplateId { get; set; }
        public string Subject { get; set; }
        public string BodyHtml { get; set; }
        public bool Activo { get; set; }
    }
}
