//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NegociosElectronicosII.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NE_VehiculoImagen
    {
        public int VehiculoImagenId { get; set; }
        public string Ruta { get; set; }
        public string Nombre { get; set; }
        public string Extension { get; set; }
        public int VehiculoId { get; set; }
    
        public virtual NE_Vehiculo NE_Vehiculo { get; set; }
    }
}
